GET http://localhost:8080/




###
GET http://localhost:8080/details/1



###
POST  http://localhost:8080/add
Content-Type: application/json

{
    "brand":"Ferrari",
    "model":"F40",
    "horsePower":478,
    "color":"Red"
}

###
POST  http://localhost:8080/add
Content-Type: application/json

{
    "id":4,
    "brand":"Ferrari",
    "model":"F50",
    "horsePower":478,
    "color":"Black"
}

###
GET http://localhost:8080/delete/4
